// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// complk_dyn_cpp
List complk_dyn_cpp(arma::cube Y, arma::vec piv, arma::mat Pi, arma::mat Psi, arma::umat Ub, int k, int n, int TT);
RcppExport SEXP _hdsbm_complk_dyn_cpp(SEXP YSEXP, SEXP pivSEXP, SEXP PiSEXP, SEXP PsiSEXP, SEXP UbSEXP, SEXP kSEXP, SEXP nSEXP, SEXP TTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type piv(pivSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Pi(PiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Psi(PsiSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type Ub(UbSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type TT(TTSEXP);
    rcpp_result_gen = Rcpp::wrap(complk_dyn_cpp(Y, piv, Pi, Psi, Ub, k, n, TT));
    return rcpp_result_gen;
END_RCPP
}
// greedy_search_cpp_original
List greedy_search_cpp_original(arma::cube Y, arma::umat Ub, arma::mat Psi, arma::mat Pi, arma::vec piv);
RcppExport SEXP _hdsbm_greedy_search_cpp_original(SEXP YSEXP, SEXP UbSEXP, SEXP PsiSEXP, SEXP PiSEXP, SEXP pivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type Ub(UbSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Psi(PsiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Pi(PiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type piv(pivSEXP);
    rcpp_result_gen = Rcpp::wrap(greedy_search_cpp_original(Y, Ub, Psi, Pi, piv));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hdsbm_complk_dyn_cpp", (DL_FUNC) &_hdsbm_complk_dyn_cpp, 8},
    {"_hdsbm_greedy_search_cpp_original", (DL_FUNC) &_hdsbm_greedy_search_cpp_original, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_hdsbm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
