# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

complk_dyn_cpp <- function(Y, piv, Pi, Psi, Ub, k, n, TT) {
    .Call(`_hdsbm_complk_dyn_cpp`, Y, piv, Pi, Psi, Ub, k, n, TT)
}

greedy_search_cpp_original <- function(Y, Ub, Psi, Pi, piv) {
    .Call(`_hdsbm_greedy_search_cpp_original`, Y, Ub, Psi, Pi, piv)
}

